# TSIA202a - Second Practice Session : Spectral density estimation and periodogram
The goal of this second session is to provide a power spectral density estimator of a real, zero-mean, weakly stationary process $X_t$. We suppose that we have access to $n$ observations and we will use the FFT algorithm (that implements the DFT) using `numpy.fft.fft`.
Recall (from the course) that the periodogram of the observations $X_0, \dots, X_{n-1}$ can be given as:
$$
I_n(\lambda) = \frac{1}{2\pi n}|\sum_{k=0}^{n-1} X_k e^{i\lambda k}|^2
$$

Moreover, the Hertglotz theorem provides a relation between the empirical autocovariance $\hat{\gamma}_n$ and the periodogram $I_n$:
$$
\hat{\gamma}_n(k) = \int_{0}^{2\pi}e^{i\lambda k}I_n({\lambda})d\lambda
$$

1. For a given $m \geq n$  we denote also the DFT as:
$$
DFT(X,m)(k) = \sum_{h=0}^{n-1}X_he^{-2i\pi\frac{kh}{m}}
$$
Show the following relation: 
$$I_n(\frac{2\pi k}{m}) = \frac{1}{2\pi n} |DFT(X,m)(k)|^2$$
2. provide a script that compute those $I_n(\frac{2\pi k}{m})$ for the time series mentioned in the first practice session
3. Show that $I_n(\lambda) = \frac{1}{2\pi} \sum_{k=0}^{n-1} \hat{\gamma}_n(k)e^{-i\lambda k}$
4. How to choose $m$ in order to get a simple relation between $\hat{\gamma}_n(k)$ and $I_n(\frac{2\pi k}{m})$ ? At the end, given a specific $\tilde{m}$ show that:
$$
\hat{\gamma}_n(k) = \frac{1}{n} IDFT\left(\left|DFT(X, \tilde{m})\right|^2, \tilde{m}\right)(k)
$$ Try this estimator on the autocovariance of previous time series of the first session.

5. In the case of white noise, estimate the variance of the periodogram for several values of $n$ and discuss about it.




### Question 1

\begin{align*}
\frac{1}{2\pi n} |DFT(X,m)(k)|^2 &= \frac{1}{2\pi n} |DFT(X,m)(k)|^2\\
&= \frac{1}{2\pi n} |\sum_{h=0}^{n-1}X_he^{-2i\pi\frac{kh}{m}}|^2 \\
&= I_n(\frac{2\pi k}{m}) 


\end{align*}

### Question 2

In [8]:
import numpy as np
import matplotlib.pyplot as plt

In [9]:
wn= 3 # sigma 
t=100
Z= np.random.normal(0, wn, t)

In [10]:
def In2(X, m):
    return 1/(2*np.pi*len(X))*np.abs(np.fft.fft(X,m))**2


In [11]:
In2(Z,120)

array([4.51508453, 2.13290226, 0.87259366, 1.11324248, 0.01101163,
       0.34376469, 0.1349098 , 0.26158956, 1.11555004, 0.28496842,
       1.54093572, 0.34785358, 2.58023527, 2.74616076, 3.37009898,
       2.03366698, 4.68996979, 0.72332441, 1.90640692, 0.8573554 ,
       0.68422768, 0.36801765, 3.53798719, 0.28929877, 3.72652475,
       0.82377451, 1.0037169 , 3.41438112, 2.53432159, 1.15697973,
       0.92590327, 0.3467642 , 0.36507983, 0.79101813, 0.68012106,
       0.39917579, 1.15510599, 6.25232425, 2.04363458, 0.21030133,
       3.05761077, 2.42189153, 0.45830167, 3.36808708, 1.16594407,
       0.32154135, 1.3182193 , 2.46157582, 1.63600968, 0.99149681,
       0.22255576, 2.29081087, 1.02022014, 2.96299908, 1.7457458 ,
       0.42047367, 6.54892014, 0.06695744, 1.32371195, 0.05635492,
       0.27506151, 0.05635492, 1.32371195, 0.06695744, 6.54892014,
       0.42047367, 1.7457458 , 2.96299908, 1.02022014, 2.29081087,
       0.22255576, 0.99149681, 1.63600968, 2.46157582, 1.31821

### __Question 3__

First, let's substitute the expression for $I_n(\lambda)$ into the equation for $\hat{\gamma}_n(k)$:

\begin{align}
\hat{\gamma}_n(k) = \int_{0}^{2\pi} e^{i\lambda k} \left( \frac{1}{2\pi n} \left| \sum_{m=0}^{n-1} X_m e^{i\lambda m} \right|^2 \right) d\lambda \\
\hat{\gamma}_n(k) = \frac{1}{2\pi n}\int_{0}^{2\pi} e^{i\lambda k} \left| \sum_{m=0}^{n-1} X_m e^{i\lambda m} \right|^2 d\lambda \\
\end{align}
Which is equal by using the conjugate 
\begin{align}
\hat{\gamma}_n(k) =\frac{1}{2\pi n}*\int_{0}^{2\pi} e^{i\lambda k} \left( \sum_{l=0}^{n-1} X_l e^{i\lambda l} \right) \left( \sum_{m=0}^{n-1} X_m e^{i\lambda m} \right)^* d\lambda\\ 
\hat{\gamma}_n(k) =\frac{1}{2\pi n}*\int_{0}^{2\pi} e^{i\lambda k} \left( \sum_{l=0}^{n-1} X_l e^{i\lambda l} \right) \left( \sum_{m=0}^{n-1} X_m e^{-i\lambda m} \right) d\lambda\\
\hat{\gamma}_n(k) =\frac{1}{2\pi n}*\sum_{l=0}^{n-1} \sum_{m=0}^{n-1} X_l X_m   \int_{0}^{2\pi} e^{i\lambda (k+l-m)}   d\lambda\\
\end{align}

And we have : $$ \int_{0}^{2\pi} e^{i\lambda (k+l-m)} \not = 0 \quad \text{if and only if } \; k+l-m = 0 \\ $$
$$\int_{0}^{2\pi} e^{i\lambda (k+l-m)} =2\pi \quad \text{if } \; k+l-m =0 \\ $$

Conditions on k implies that k must be below n for the previous equation to not be equal 0  
  

Therefore :  
\begin{align}
\hat{\gamma}_n(k) =\frac{1}{n} \sum_{l=0}^{n-1} \sum_{m=0}^{n-1} X_l X_m *\delta_{k+l-m}\\
\hat{\gamma}_n(k) =\frac{1}{n} \sum_{m=0}^{n-1} X_{m-k} X_m \\
\end{align}

So, 
\begin{align*}
\frac{1}{2\pi} \sum_{k=0}^{n-1} \hat{\gamma}_n(k)e^{-i\lambda k} &= \frac{1}{2\pi n} \sum_{k=0}^{n-1}\sum_{m=0}^{n-1} X_{m-k} X_m e^{-i\lambda k}\\
&= \frac{1}{2\pi n}  \sum_{k=0}^{n-1}\sum_{m=0}^{n-1} X_{m-k} X_m e^{i\lambda(m-k)} e^{i\lambda m}\\
&= \frac{1}{2\pi n}  \sum_{m=0}^{n-1}\sum_{k=0}^{m} (X_{m-k}  e^{i\lambda(m-k)}) X_m e^{i\lambda m}\\
&= \frac{1}{2\pi n}  \sum_{0\leq k \leq m\leq n-1}(X_{k}  e^{i\lambda k}) X_m e^{i\lambda m}\\
\end{align*}

### __Question 4__

Si on choisit m=n on obtient  

$$
I_n(\frac{2\pi k}{n})  = \frac{1}{2\pi} \sum_{h=0}^{n-1} \hat{\gamma}_n(h)e^{-2i\pi \frac{hk}{n} }\\
$$

Donc  

\begin{align*}
\frac {2\pi n} n I_n(\frac{2\pi k}{n})=  DFT(\hat{\gamma},n)(k) \\
\hat{\gamma}_n(k) = IDFT(\frac {2\pi n} n I_n(\frac{2\pi k}{n}))
\end{align*}
et d'après la question 1 on a :  

\begin{align*}
\hat{\gamma}_n(k) &= IDFT(\frac 1 n |DFT(X,n)|^2,n)(k) \\
&=\frac 1 n IDFT( |DFT(X,n)|^2,n)(k)

\end{align*}

On a donc bien pour $\tilde{m}=n$ : 
$$\hat{\gamma}_n(k) = \frac{1}{n} IDFT\left(\left|DFT(X, \tilde{m})\right|^2, \tilde{m}\right)(k)$$

### Question 5 


In [12]:
n= np.arange(100,1000,50)
wn= 3 
Z=[ np.random.normal(0, wn, k) for k in n]
lamb=1

In= [In2(Z[k],lamb) for k in range(len(n))]

In [13]:
def auv(X):
    n=len(X)
    X_cov= np.zeros(n)
    m = np.mean(X)
    for h in range(n):
        X_cov[h]= (1/n) *sum((X[t+h]-m)*(X[t]-m) for t in range(n-h))
    return X_cov



In [14]:
Variance = [auv(In[k]) for k in range(len(n))]

In [15]:
Variance

[array([ 2.53824879e-04, -4.23041465e-05, -8.46082931e-05]),
 array([ 1.22739117e-04, -2.04565195e-05, -4.09130391e-05]),
 array([ 2.86075159e-05, -4.76791932e-06, -9.53583865e-06]),
 array([ 8.31533708e-07, -1.38588951e-07, -2.77177903e-07]),
 array([ 2.46841869e-05, -4.11403116e-06, -8.22806231e-06]),
 array([ 0.00127089, -0.00021181, -0.00042363]),
 array([ 3.62328652e-04, -6.03881087e-05, -1.20776217e-04]),
 array([ 0.00111487, -0.00018581, -0.00037162]),
 array([ 0.00162143, -0.00027024, -0.00054048]),
 array([ 0.00152724, -0.00025454, -0.00050908]),
 array([ 3.80067611e-04, -6.33446019e-05, -1.26689204e-04]),
 array([ 5.30555022e-07, -8.84258370e-08, -1.76851674e-07]),
 array([ 3.14036062e-04, -5.23393437e-05, -1.04678687e-04]),
 array([ 8.40810432e-05, -1.40135072e-05, -2.80270144e-05]),
 array([ 9.36582880e-07, -1.56097147e-07, -3.12194293e-07]),
 array([ 8.95147264e-05, -1.49191211e-05, -2.98382421e-05]),
 array([ 8.21927348e-05, -1.36987891e-05, -2.73975783e-05]),
 array([ 9.